export { default as MyPage } from '@pages/mypage/MyPage';
export { default as MyPageEdit } from '@pages/mypage/MyPageEdit';
export { default as MyPageMyInfo } from '@pages/mypage/MyPageMyInfo';
export { default as MyPageList } from '@pages/mypage/list/MyPageClassList';
export { default as MyPageNoAuth } from '@pages/mypage/list/MyPageList';
export { default as MyPageClassList } from '@pages/mypage/list/MyPageList';
export { default as MyPageJoinList } from '@pages/mypage/list/MyPageJoinList';
export { default as MyPageRecipeList } from '@pages/mypage/list/MyPageRecipeList';
export { default as MyPageBookmarkList } from '@pages/mypage/list/bookmark/MyPageBookmarkList';
